### ISSUE TITLE
[Question] Usage of NuHamil code

### ISSUE THREAD

**Issue by SotaYoshida** [Takayuki-Miyagi/NuHamil-public#1]
Hi Miyagi-san!! 😃 

I hope you are doing well. Thank you for sharing this NuHamil code!

As you may know, I have made a Julia package [NuclearToolkit.jl](https://github.com/SotaYoshida/NuclearToolkit.jl) and I've been working on it.
I have done to implement a new feature in the dev branch (just today) to calculate locally regularized genuine 3NF in antisymmetrized Jacobi HO basis, i.e., P.Navratil's 3NF (including non-locally regularized cD&cE terms).

Since one can develop extremely shorter codes with Julia (compared to C++/Fortran) to do similar things
with the help of high readability and packages of the Julia language (without losing efficiency),
I was trying to develop my own code to 
* translate 3NF into a single-particle basis w/ novel normal ordering techniques by you or one by K. Hebeler in Jacobi momentum space
* 3NF with nonlocal/lnl regulators
* SRG stuffs

Now, I have something to ask you. Would it be OK to use your code for such development?
I will not translate your code or do anything violating GPL v3.0, but develop similar stuffs in a different and "Julian" manner  using your matrix elements as guidelines, and you (and your code) will be properly acknowledged.

I would be happy if I could give you some cross checks and we could make complementary contributions to each other's codes. Please let me know your thoughts (and feel free to close the issue). Thanks!

**Comment by Takayuki-Miyagi** [comment]
Glad to hear that you are interested in the code!
Also I am happy with that you use the code for your developments.
